In [1]:
import torch
torch.__version__


'2.13.0+cpu'

## What is Tensor?

### Ans: so basically it is a way of representing data using numbers, the data could be in form of text, images and videos etc

In [2]:
# Creating a scalar
scalar=torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim # to check  the dimension of the tensor


0

In [4]:
# get the number within the tensor (this works only with a single number tensor)
scalar.item()


7

In [5]:
# Creating a vector (A vector is a single dimension tensor but can contain many numbers like [2,3] representing the number of [bedrooms,bathrooms])
vector=torch.tensor([2,3])
vector


tensor([2, 3])

In [6]:
vector.ndim # Vector is 1D tensor so the result should be 1


1

In [7]:
vector.shape # it will return the count of the elements that are in the tensor, in  the vector as there are two elements so the result should be 2


torch.Size([2])

In [8]:
# creating a matrix
matrix=torch.tensor([[1,2],
                    [3,4]])
matrix


tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim


2

In [10]:
matrix.shape # the result of a matrix will give the count as nxn


torch.Size([2, 2])

In [11]:
# Creating a tensor (which differs from matrix in a sense that matrix is 2 elements deep and 2 elements wide)
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]
                      ]])
Tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
Tensor.ndim


3

In [13]:
Tensor.shape # The result [1,3,3] shows that there is one dimension of 3 x 3


torch.Size([1, 3, 3])

## Random tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

**Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using **torch.rand()** and passing in the size parameter.

In [14]:
# Creating a random tensor
random_tensor=torch.rand(size=(3,4)) # size=(height, width)
random_tensor,random_tensor.dtype


(tensor([[0.7649, 0.5960, 0.0956, 0.4699],
         [0.3070, 0.6729, 0.0096, 0.6758],
         [0.7109, 0.2568, 0.7833, 0.9962]]),
 torch.float32)

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [15]:
# Creating a  random tensor of size (224, 224, 3)
random_image_size_tensor=torch.rand(224,224,3)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

Zeros and ones¶
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the **size** parameter comes into play.

In [16]:
# Creating a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# WE CAN ALSO DO THE SAME TO CREATE A TENSOR OF ALL ONES

# Creating a tensor of all ones
ones=torch.ones(size=(3,4))
ones,ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

*Note*: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [18]:
# Using the torch.arange(), torch.range() is deprecated
zero_to_10_deprecated=torch.range(0,10) # This may return an error in the future

# Creating a range of values 0 to 10
zero_to_10=torch.arange(start=0, end=10, step=1)
zero_to_10


C:\Users\SMART COM\AppData\Local\Temp\ipykernel_16100\2699783525.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_10_deprecated=torch.range(0,10) # This may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use **torch.zeros_like(input)** or **torch.ones_like(input)** which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [19]:
# Creating a tensor of zeros with same shape as another tensor(like zero_to_10)
ten_zeros=torch.zeros_like(input=(zero_to_10))
ten_zeros,ten_zeros.shape


(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

# Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.**cuda** anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

**Note:** An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

**Resources:**

* See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
* Read the [Wikipedia page for an overview of what precision in computing](<https://en.wikipedia.org/wiki/Precision_(computer_science>)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [20]:
# Default data type for tensors is float32
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                             device=None, # defaults to None, which use the default tensor type
                             requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are **datatype and device issues**.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

For now let's create a tensor with **dtype=torch.float16**.

In [21]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16) # torch.half would also works
float_16_tensor.dtype


torch.float16

# Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

* shape - what shape is the tensor? (some operations require specific shape rules)
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CP*U)

Let's create a random tensor and find out details about it.

In [22]:
# Creating a tensor
some_tensor=torch.tensor([3,4])

# Find out details of the tensor
print(some_tensor)
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Device Tensor stored on: {some_tensor.device}") # The default will be cpu


tensor([3, 4])
Shape of Tensor: torch.Size([2])
Datatype of Tensor: torch.int64
Device Tensor stored on: cpu


**Note:** When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

* "what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

# Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

# Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [23]:
# Create a tensor of some values and then add a number to it
tensor=torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [24]:
# Multiply it with 10
tensor * 10


tensor([10, 20, 30])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.



In [25]:
# Tensor don't change unless reassigned
tensor


tensor([1, 2, 3])

Let's subtract a number and this time we'll reassign the tensor variable.



In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor


tensor([-9, -8, -7])

In [27]:
# Add and reassign
tensor = tensor + 10
tensor


tensor([1, 2, 3])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [28]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, '*', tensor)
print("Equals:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])



# Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

**Resource:** You can see all of the rules for matrix multiplication using torch.matmul() [in the PyTorch documentation.](https://pytorch.org/docs/stable/generated/torch.matmul.html)

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [29]:
# Creating a tensor
tensor= torch.tensor([1,2,3])
tensor.shape


torch.Size([3])

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:


| Operation | Calculation | Code |
|---|---|---|
| Element-wise multiplication | `[1 × 1, 2 × 2, 3 × 3] = [1, 4, 9]` | `tensor * tensor` |
| Matrix multiplication | `[1 × 1 + 2 × 2 + 3 × 3] = [14]` | `tensor.matmul(tensor)` |


In [30]:
# Element-wise multiplication
tensor * tensor


tensor([1, 4, 9])

In [31]:
#  Matrix multiplication
tensor.matmul(tensor)


tensor(14)

In [32]:
# Can also use the symbol "@" for matrix multiplcation, although not recommended

tensor @ tensor


tensor(14)


You can do matrix multiplication by hand but it's not recommended.

The in-built **torch.matmul()** method is faster.

In [33]:
%%time
# Matrix multiplication by hand
# (avoid  doing operation using with for loop at all cost, they are computationaly expensive)

value=0
for i in range (len(tensor)):
    value += tensor[i] * tensor[i]
value


CPU times: total: 0 ns
Wall time: 4.43 ms


tensor(14)

In [34]:
%%time
torch.matmul(tensor,tensor)


CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

# One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [35]:
tensor_A= torch.tensor([[1,2],
                        [2,3],
                        [4,5]],dtype=torch.float32)
tensor_B= torch.tensor([[7,10],
                        [8,11],
                        [9,12]],dtype=torch.float32)
torch.matmul(tensor_A,tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* **torch.transpose(input, dim0, dim1)** - where **input** is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

Let's try the latter.   

In [36]:
# View tensor_A and tensor_B
tensor_A,tensor_B


(tensor([[1., 2.],
         [2., 3.],
         [4., 5.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [37]:
# View tensor_A and tensor_B.T
tensor_A,tensor_B.T


(tensor([[1., 2.],
         [2., 3.],
         [4., 5.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [38]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.shape} <- inner dimensions match\n")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([3, 2]) <- inner dimensions match

Output:

tensor([[27., 30., 33.],
        [44., 49., 54.],
        [78., 87., 96.]])

Output shape: torch.Size([3, 3])


In [39]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear=torch.nn.Linear(in_features=2,
                       out_features=6)
x=tensor_A
output=linear(x)
print(f' Input Shape: {x.shape}\n')
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


 Input Shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [3.3644, 1.7131, 0.4592, 0.4575, 0.2355, 1.7308],
        [5.6194, 2.6809, 0.4347, 0.5995, 0.4447, 3.2247]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [40]:
# Creating a tensor
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Now lets perform some aggregation
print(f'Minimum: {x.min()}\n')
print(f'Maximum: {x.max()}\n')
print(f'Sum: {x.sum()}\n')
# print(f'Mean: {x.mean()}\n')
print(f'Mean: {x.type(torch.float32).mean()}\n')


Minimum: 0

Maximum: 90

Sum: 450

Mean: 45.0



In [42]:
torch.sum(x),torch.min(x),torch.max(x),torch.mean(x.type(torch.float32))


(tensor(450), tensor(0), tensor(90), tensor(45.))

In [43]:
# Creating a tensor
tensor= torch.arange(0,100,10)
print(f"Tensor: {tensor}")

# Return the index of the min and max values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


In [44]:
# Changing the tensor datatype

# Creating a tensor and checking it's datatype
tensor= torch.arange(10.,100.,10.)
tensor.dtype


torch.float32

In [45]:
# Now we will change the datatype of the above tensor to float16
tensor_float16=tensor.type(torch.float16)
tensor_float16.dtype


torch.float16

In [46]:
# Creating the int8 tensor

tensor_int8= tensor.type(torch.int8)
tensor_int8.dtype


torch.int8

In [47]:
x= torch.arange(1.,8.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [48]:
x_reshaped=x.reshape(1,7)
x_reshaped,x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z=x.view(1,7)
z,x


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [50]:
# Changing the z also gonna change the x as well
z[:,0]=5
z,x


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [51]:
# Stacking tensors on top of each other
stacked_tensors= torch.stack([x,x,x,x],dim=1)
stacked_tensors.shape,stacked_tensors


(torch.Size([7, 4]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]))

In [52]:
# Now we are going to remove the dimension from the trensor

print(f'Previous Tensor: {x_reshaped}')
print(f'Previous Shape: {x_reshaped.shape}')

# Now we are removing the extra dimension from the tensor using the squeezed
x_squeezed=x_reshaped.squeeze()
print(f"\n New Tensor: {x_squeezed}")
print(f"\n New Shape: {x_squeezed.shape}")


Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous Shape: torch.Size([1, 7])

 New Tensor: tensor([5., 2., 3., 4., 5., 6., 7.])

 New Shape: torch.Size([7])


In [53]:
# We can also do the reverse using the unsqueeze function to add a dimension value of 1 at a specific index
print(f'Previous Tensor: {x_squeezed}')
print(f'Previous Shape: {x_squeezed.shape}')

# Adding an extra dimension using the unsqueeze
x_unsqueeze=x_squeezed.unsqueeze(dim=0)
print(f'New Tensor: {x_unsqueeze}')
print(f'New Shape: {x_unsqueeze.shape}')


Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous Shape: torch.Size([7])
New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New Shape: torch.Size([1, 7])


In [54]:
# You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

x_original=torch.rand(3,3,4)
x_original


tensor([[[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]],

        [[0.9516, 0.0753, 0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779, 0.9040],
         [0.5547, 0.3423, 0.6343, 0.3644]],

        [[0.7104, 0.9464, 0.7890, 0.2814],
         [0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103]]])

In [55]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
print(x[0])
print(x[0][0])
print(x[0][0][0])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [57]:
x[:,0]


tensor([[1, 2, 3]])

In [58]:
x[:,:,1]


tensor([[2, 5, 8]])

In [59]:
y=torch.rand(2,2,3) # 1 represents the number of layers , 2 represents number of rows and 3 represents number of columns
y.ndim,y


(3,
 tensor([[[0.6440, 0.7071, 0.6581],
          [0.4913, 0.8913, 0.1447]],
 
         [[0.5315, 0.1587, 0.6542],
          [0.3278, 0.6532, 0.3958]]]))

In [60]:
y[1,1,2]


tensor(0.3958)

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,1,1]


tensor([5])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]


tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0,0,:]


tensor([1, 2, 3])

In [64]:
# Numoy array to tensor

import numpy as np

array=np.arange(1.0,8.0)

tensor= torch.from_numpy(array).type(torch.float32)# we will type cast the tensor as most of the operations of tensors using the float32 and numpy default dtype is float64
tensor,tensor.dtype


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [65]:
# as we are reassigning the array to a tensor so any changes in the array do not gonna affect the tensor

array += 1
array,tensor


(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [66]:
# Tensor to numpy array
tensor=torch.arange(1.0,8.0)

numpy_tensor = tensor.numpy()
tensor,numpy_tensor


(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [67]:
# Similar to above case if we change the original tensor than it won't gonna change the new tensor
tensor += 1
tensor,numpy_tensor


(tensor([2., 3., 4., 5., 6., 7., 8.]),
 array([2., 3., 4., 5., 6., 7., 8.], dtype=float32))

In [68]:
print(id(tensor))
print(id(numpy_tensor))


2161665347008
2161641994256


### Reproducibility of tensors

In [70]:
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)


print(f'Random Tensor A: {tensor_A}\n')
print(f'Random Tensor B: {tensor_B}\n')

print("Does tensor A equals to tensor B (anywhere)")

tensor_A == tensor_B


Random Tensor A: tensor([[0.6057, 0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578, 0.3313],
        [0.3227, 0.0162, 0.2137, 0.6249]])

Random Tensor B: tensor([[0.4340, 0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624, 0.1816],
        [0.9998, 0.5944, 0.6541, 0.0337]])

Does tensor A equals to tensor B (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [71]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(f'Random Tensor c: {random_tensor_c}\n')
print(f'Random Tensor d: {random_tensor_d}\n')

print("Does tensor A equals to tensor B (anywhere)")

random_tensor_c == random_tensor_d


Random Tensor c: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random Tensor d: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does tensor A equals to tensor B (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Exercise

In [82]:
random_seed = 0
torch.manual_seed(seed=random_seed)
random_tensor1 = torch.rand(7,7)
random_tensor1


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [86]:
random_seed = 0
torch.manual_seed(seed=random_seed)
random_tensor2 = torch.rand(1,7)
random_tensor2

random_tensor1 == random_tensor2
torch.mm(random_tensor2,random_tensor1)


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])

In [89]:
torch.rand(1,1,1,10)


tensor([[[[0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507,
           0.0317, 0.2081]]]])