In [1]:
import torch
torch.__version__


'2.13.0+cpu'

## What is Tensor?

### Ans: so basically it is a way of representing data using numbers, the data could be in form of text, images and videos etc

In [2]:
# Creating a scalar
scalar=torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim # to check  the dimension of the tensor


0

In [5]:
# get the number within the tensor (this works only with a single number tensor)
scalar.item()


7

In [6]:
# Creating a vector (A vector is a single dimension tensor but can contain many numbers like [2,3] representing the number of [bedrooms,bathrooms])
vector=torch.tensor([2,3])
vector


tensor([2, 3])

In [7]:
vector.ndim # Vector is 1D tensor so the result should be 1


1

In [9]:
vector.shape # it will return the count of the elements that are in the tensor, in  the vector as there are two elements so the result should be 2


torch.Size([2])

In [12]:
# creating a matrix
matrix=torch.tensor([[1,2],
                    [3,4]])
matrix


tensor([[1, 2],
        [3, 4]])

In [15]:
matrix.ndim


2

In [17]:
matrix.shape # the result of a matrix will give the count as nxn


torch.Size([2, 2])

In [19]:
# Creating a tensor (which differs from matrix in a sense that matrix is 2 elements deep and 2 elements wide)
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]
                      ]])
Tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
Tensor.ndim


3

In [22]:
Tensor.shape # The result [1,3,3] shows that there is one dimension of 3 x 3


torch.Size([1, 3, 3])

## Random tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

**Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using **torch.rand()** and passing in the size parameter.

In [27]:
# Creating a random tensor
random_tensor=torch.rand(size=(3,4)) # size=(height, width)
random_tensor,random_tensor.dtype


(tensor([[0.1865, 0.2829, 0.4902, 0.6644],
         [0.5233, 0.5816, 0.0631, 0.8223],
         [0.8395, 0.1994, 0.5091, 0.4180]]),
 torch.float32)

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [28]:
# Creating a  random tensor of size (224, 224, 3)
random_image_size_tensor=torch.rand(224,224,3)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

Zeros and ones¶
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the **size** parameter comes into play.

In [30]:
# Creating a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [31]:
# WE CAN ALSO DO THE SAME TO CREATE A TENSOR OF ALL ONES

# Creating a tensor of all ones
ones=torch.ones(size=(3,4))
ones,ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

*Note*: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [34]:
# Using the torch.arange(), torch.range() is deprecated
zero_to_10_deprecated=torch.range(0,10) # This may return an error in the future

# Creating a range of values 0 to 10
zero_to_10=torch.arange(start=0, end=10, step=1)
zero_to_10


C:\Users\SMART COM\AppData\Local\Temp\ipykernel_2092\447407219.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_10_deprecated=torch.range(0,10) # This may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use **torch.zeros_like(input)** or **torch.ones_like(input)** which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [36]:
# Creating a tensor of zeros with same shape as another tensor(like zero_to_10)
ten_zeros=torch.zeros_like(input=(zero_to_10))
ten_zeros,ten_zeros.shape


(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

# Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.**cuda** anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

**Note:** An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

**Resources:**

* See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
* Read the [Wikipedia page for an overview of what precision in computing](<https://en.wikipedia.org/wiki/Precision_(computer_science>)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [37]:
# Default data type for tensors is float32
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                             device=None, # defaults to None, which use the default tensor type
                             requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are **datatype and device issues**.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

For now let's create a tensor with **dtype=torch.float16**.

In [40]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16) # torch.half would also works
float_16_tensor.dtype


torch.float16